[WIP] Feature/aws modifications
radon-h2020/radon-particles pull request #43
Opened 2020-08-31 09:37 UTC by v-yussupov

This PR introduces several enhancements for AWS-specific node types, namely:

1. AWS API Gateway node type can be used together with AwsApiGatewayTriggers relationship type to generate and deploy APIs for connected AWS Lambda functions.
2. Deployable AWS DynamoDBTable node type is added
3. ServerlessToDoListAPI Service Template is added to demonstrate a simple serverless API deployment using AWS services
4. Ansible implementation of AWS Lambda functions supports attaching artifacts on the level of node templates
5. Other minor modifications in AWS-related types

## Resolving Issue / Feature

As one of the introduced modifications, this PR fixes #17 

- [x] Ensure that the commit message is [a good commit message](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Ensure to use auto format in **all** files

2020-08-31 09:41 UTC, v-yussupov commented
For compatibility reasons, this PR is to be merged after #37

2020-08-31 12:40 UTC, miwurster approved these changes
Very good job @v-yussupov !!

2020-09-02 11:32 UTC, miwurster requested changes

2020-09-02 11:32 UTC, miwurster commented on servicetemplates/radon.blueprints/ThumbnailGeneration/LICENSE
> +                                 Apache License
Apply the RADON license

2020-09-02 11:32 UTC, miwurster commented on servicetemplates/radon.blueprints/ServerlessToDoListAPI/LICENSE
> +
Apply the RADON license

2020-09-03 08:45 UTC, miwurster approved these changes

2020-09-03 08:46 UTC, merged