New node types OpenFaaS, google cloud storage
radon-h2020/radon-particles pull request #58
Opened 2020-09-25 15:40 UTC by chinmaya-dehury

- [ ] Ensure that the commit message is [a good commit message](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Ensure to use auto format in **all** files

---

## Short Description
In this version, we (@chinmaya-dehury , @pjakovits ) have added node types to invoke OpenFaaS function, read/write data from/to Google cloud storage.

## Resolving Issue / Feature

2020-09-28 12:24 UTC, miwurster requested changes
Could you please "touch" all your types and make sure that they are fully processable by Winery?

You could use the internal "touch type" feature in the admin tab of Winery: 
![image](https://user-images.githubusercontent.com/2610997/94431880-2e649d00-0196-11eb-8e84-1b30bdff9824.png)

Please make also sure you are using the latest version of Winery:
```
docker pull opentosca/raond-gmt
```

2020-09-28 14:40 UTC, chinmaya-dehury commented
Thanks @miwurster for your suggestion. I'll make sure that the branch passes through "`touch`" command.

2020-09-28 15:13 UTC, miwurster commented
Don't worry if see the structure of the resulting TOSCA files change. In one of the latest Winery versions, we added a couple of changes in tuning/improving the serialization of TOSCA files ;-)

2020-09-30 05:33 UTC, miwurster approved these changes

2020-09-30 05:34 UTC, merged